# HOMEWORK-1 [Pandas and NumPy Exercise for Data Analysis]

# Name: MD. Rafsan Jamil

# Roll   : 20231056

# Objective: 
      1. To learn about numpy and pandas library 
      2. To learn about numpy excercise
      3. To learn about pandas dataframe and series

# 1. Numpy Array Exercises 

In [1]:
# import numpy library
import numpy as np

In [5]:
# Create a Numpy array filled with all zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
# Create a full numpy array
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [25]:
# Create a Numpy array filled with all ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
# Combining a one and a two-dimensional NumPy Array
# One-dimensional array
array1 = np.array([1, 2,3])

# Two-dimensional array
array2 = np.array([[4, 5, 6],
                   [7, 8, 9]])

# Reshape array1 to have shape (1, 3)
reshaped_array1 = array1.reshape(1, 3)

# Concatenate the arrays along axis 0 (rows)
combined_array = np.concatenate((reshaped_array1, array2), axis=0)
print(combined_array)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# Counts the number of non-zero values in the array
# Example array
array = np.array([[1, 0, 3],
                  [0, 2, 0],
                  [4, 0, 5]])

# Count the number of non-zero values
count = np.count_nonzero(array)

print(count)


5


# 2. Numpy Matrix Exercises

In [29]:
# Get the maximum value from given matrix
# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the maximum value from the matrix
max_value = np.max(matrix)

print(max_value)

9


In [30]:
# Get the minimum value from given matrix
# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the minimum value from the matrix
min_value = np.min(matrix)

print(min_value)

1


In [31]:
# Find the number of rows and columns of a given matrix using NumPy
# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the number of rows and columns of the matrix
rows, columns = matrix.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 3
Number of columns: 3


In [32]:
# Adding and Subtracting Matrices in Python
# Example matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Addition of matrices
addition_result = matrix1 + matrix2

# Subtraction of matrices
subtraction_result = matrix1 - matrix2

print("Addition Result:")
print(addition_result)

print("Subtraction Result:")
print(subtraction_result)

Addition Result:
[[ 8 10 12]
 [14 16 18]]
Subtraction Result:
[[-6 -6 -6]
 [-6 -6 -6]]


In [35]:
# Matrix Multiplication in NumPy
# Example matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Matrix multiplication using matmul()
multiplication_result = np.matmul(matrix1, matrix2)
print("Multiplication Result:")
print(multiplication_result)

Multiplication Result:
[[ 58  64]
 [139 154]]


In [37]:
# Ways to add row/columns in numpy array
# Example array
array = np.array([[1, 2],
                  [3, 4]])

# Add a row at index 1 using insert()
new_row = np.array([5, 6])
array_with_row = np.insert(array, 1, new_row, axis=0)

print("Array with added row:")
print(array_with_row)

# Add a column at index 1 using insert()
new_column = np.array([7, 8])
array_with_column = np.insert(array, 1, new_column, axis=1)

print("Array with added column:")
print(array_with_column)


Array with added row:
[[1 2]
 [5 6]
 [3 4]]
Array with added column:
[[1 7 2]
 [3 8 4]]


In [3]:
# Get the eigen values of a matrix
# Example matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Get the eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(matrix)

print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[-0.37228132  5.37228132]


In [4]:
#How to count the frequency of unique values in NumPy array?

# Create a NumPy array
arr = np.array([1, 2, 3, 2, 1, 3, 4, 5, 4])

# Get the counts of unique values
value_counts = np.bincount(arr)

# Print the unique values and their counts
for value, count in enumerate(value_counts):
    if count > 0:
        print(f"{value}: {count}")


1: 2
2: 2
3: 2
4: 2
5: 1


In [3]:
# How to inverse a matrix using NumPy
# Ceate a matrix
matrix = np.array([[1, 2], [3, 4]])

# inverse matrix
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
# How to Calculate the determinant of a matrix using NumPy?

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

# Print the determinant
print("Determinant:", determinant)


Determinant: -2.0000000000000004


In [5]:
# Convert covariance matrix to correlation matrix using Python

# Define the covariance matrix
covariance_matrix = np.array([[1.0, 0.5], [0.5, 2.0]])

# Calculate the diagonal matrix of standard deviations
standard_deviations = np.sqrt(np.diag(covariance_matrix))

# Calculate the inverse of the diagonal matrix of standard deviations
inv_standard_deviations = 1.0 / standard_deviations

# Calculate the correlation matrix
correlation_matrix = covariance_matrix * inv_standard_deviations
correlation_matrix = correlation_matrix * inv_standard_deviations[:, np.newaxis]

# Print the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)


Correlation Matrix:
[[1.         0.35355339]
 [0.35355339 1.        ]]


# 3. Numpy Indexing Exercises

In [6]:
# Replace NumPy array elements that doesn’t satisfy the given condition

# Define the array
arr = np.array([1, 2, 3, 4, 5, 6])

# Replace elements that are greater than 4 with 0
arr[arr > 4] = 0

# Print the updated array
print(arr)


[1 2 3 4 0 0]


In [3]:
#Return the indices of elements where the given condition is satisfied

# Define the array
arr = np.array([1, 2, 3, 4, 5, 6])

# Find the indices where elements are greater than 4
indices = np.where(arr > 4)[0]

# Print the indices
print(indices)


[4 5]


In [4]:
#Replace negative value with zero in numpy array

# Create a sample array
arr = np.array([-1, 2, -3, 4, -5])

# Replace negative values with zero
arr = np.where(arr < 0, 0, arr)

print(arr)


[0 2 0 4 0]


In [5]:
#Replace NaN values with average of columns

# Create a sample array with NaN values
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [np.nan, 8, 9]])

# Calculate column-wise average
column_avg = np.nanmean(arr, axis=0)

# Replace NaN values with column-wise average
arr[np.isnan(arr)] = column_avg[np.isnan(arr).any(axis=0)]

print(arr)


[[1.  2.  2.5]
 [4.  5.  6. ]
 [7.5 8.  9. ]]


In [6]:
#How to get values of an NumPy array at certain index positions?

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Define index positions
indices = [1, 3]

# Get values at the specified index positions
values = arr[indices]

print(values)


[2 4]


In [7]:
#Find indices of elements equal to zero in a NumPy array

# Create a sample array
arr = np.array([1, 0, 3, 0, 5, 0])

# Find indices of elements equal to zero
indices = np.where(arr == 0)

print(indices)


(array([1, 3, 5], dtype=int64),)


In [8]:
#How to access different rows of a multidimensional NumPy array?

# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Access specific rows
row1 = arr[0]  # Access the first row
row2 = arr[1]  # Access the second row
row3 = arr[2]  # Access the third row

print(row1)
print(row2)
print(row3)


[1 2 3]
[4 5 6]
[7 8 9]


In [11]:
#How to Remove columns in Numpy array that contains non-numeric values?
# Creating 3X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 10.5],
                  [41, 52.5, 25],
                  [100, np.nan, 41]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all columns containing non-numeric elements ")
print(n_arr[:, ~np.isnan(n_arr).any(axis=0)])

Given array:
[[ 10.5  22.5  10.5]
 [ 41.   52.5  25. ]
 [100.    nan  41. ]]

Remove all columns containing non-numeric elements 
[[ 10.5  10.5]
 [ 41.   25. ]
 [100.   41. ]]


In [12]:
#Get row numbers of NumPy array having element larger than X
# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Define the threshold value
X = 5

# Get row numbers where elements are larger than X
row_numbers = np.where(np.any(arr > X, axis=1))[0]

print(row_numbers)

[1 2]


# 4. Numpy Sorting and Searching Exercises

In [13]:
# How to get the indices of the sorted array using NumPy in Python
# Create a sample array
arr = np.array([5, 1, 3, 2, 4])

# Get indices of the sorted array
sorted_indices = np.argsort(arr)

print(sorted_indices)

[1 3 2 4 0]


In [2]:
#Finding the k smallest values of a NumPy array

# Example array
arr = np.array([9, 4, 2, 7, 5, 1, 8, 6, 3])

# Number of smallest values to find
k = 3

# Use argsort to get indices that would sort the array
indices = np.argsort(arr)

# Retrieve the k smallest values using the first k indices
k_smallest = arr[indices[:k]]

print(k_smallest)


[1 2 3]


In [6]:
#How to get the n-largest values of an array using NumPy?

# Example array
arr = np.array([9, 4, 2, 7, 5, 1, 8, 6, 3])

# Number of largest values to find
n = 3

# Use argsort to get indices that would sort the array in descending order
indices = np.argsort(arr)

# Retrieve the last n indices to get the n-largest values
n_largest = arr[indices[-n:]]

print(n_largest)


[7 8 9]


In [7]:
# Sort the values in a matrix

# Example matrix
matrix = np.array([[9, 4, 2],
                   [7, 5, 1],
                   [8, 6, 3]])

# Sort the values in the matrix
sorted_matrix = np.sort(matrix)

print(sorted_matrix)


[[2 4 9]
 [1 5 7]
 [3 6 8]]


In [8]:
#Sort the values in a matrix

# Example matrix
matrix = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

# Sort the values in the matrix in ascending order
sorted_matrix = np.sort(matrix, axis=None)

print("Original Matrix:")
print(matrix)

print("\nSorted Matrix:")
print(sorted_matrix)


Original Matrix:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Sorted Matrix:
[1 2 3 4 5 6 7 8 9]


In [13]:
#Filter out integers from float numpy array
# initialising array
ini_array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
 
# printing initial array
print ("initial array : ", str(ini_array))
 
# filtering integers
result = ini_array[ini_array != ini_array.astype(int)]
 
# printing resultant
print ("final array", result)

initial array :  [1.  1.2 2.2 2.  3.  2. ]
final array [1.2 2.2]


In [14]:
#Find the indices into a sorted array

# Example array
array = np.array([9, 4, 2, 7, 5])

# Get the indices that would sort the array
sorted_indices = np.argsort(array)

print("Original Array:")
print(array)

print("\nSorted Indices:")
print(sorted_indices)


Original Array:
[9 4 2 7 5]

Sorted Indices:
[2 1 4 3 0]


# 5. Numpy Random Exercises

In [15]:
#Create a Numpy array with random values

# Create a 1D array with random values
random_array = np.random.rand(5)

print("1D Random Array:")
print(random_array)

# Create a 2D array with random values
random_matrix = np.random.rand(3, 4)

print("\n2D Random Matrix:")
print(random_matrix)


1D Random Array:
[0.43954563 0.26485058 0.01773626 0.93141077 0.02625085]

2D Random Matrix:
[[0.75634309 0.3524871  0.37470479 0.84277938]
 [0.81119838 0.96425339 0.9959382  0.7491341 ]
 [0.87075918 0.33836985 0.37205549 0.28794461]]


In [16]:
#Generate Random Numbers From The Uniform Distribution using NumPy

# Generate random numbers from the uniform distribution
random_numbers = np.random.uniform(low=0.0, high=1.0, size=5)

print("Random Numbers from Uniform Distribution:")
print(random_numbers)


Random Numbers from Uniform Distribution:
[0.36235458 0.44296586 0.14267032 0.83082728 0.09752162]


In [17]:
#Return a Matrix of random values from a uniform distribution

# Generate a matrix of random values from the uniform distribution
rows = 3
cols = 4
random_matrix = np.random.uniform(low=0.0, high=1.0, size=(rows, cols))

print("Random Matrix from Uniform Distribution:")
print(random_matrix)


Random Matrix from Uniform Distribution:
[[0.83378565 0.93171556 0.86778489 0.10140735]
 [0.63628847 0.16757091 0.24743469 0.95761479]
 [0.22489537 0.37897845 0.01581924 0.11317883]]


# 6. Dataframe Exercises

In [2]:
#Make a Pandas DataFrame with two-dimensional list
# import pandas
import pandas as pd
# create data
data = [
    ['John', 28, 'Engineer'],
    ['Sarah', 32, 'Doctor'],
    ['Michael', 45, 'Lawyer'],
    ['Emily', 29, 'Teacher']
]
#create dataframe
df = pd.DataFrame(data, columns=['Name', 'Age', 'Occupation'])

df


Name  Age Occupation
0     John   28   Engineer
1    Sarah   32     Doctor
2  Michael   45     Lawyer
3    Emily   29    Teacher

In [4]:
#Creating DataFrame from dict of narray/lists

# Dictionary containing arrays/lists
data = {
    'Name': ['John', 'Jane', 'Mike'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Creating DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)


   Name  Age      City
0  John   25  New York
1  Jane   30    London
2  Mike   35     Paris


In [5]:
#Creating Pandas dataframe using list of lists

# List of lists
data = [
    ['John', 25, 'New York'],
    ['Jane', 30, 'London'],
    ['Mike', 35, 'Paris']
]

# Creating DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

# Displaying the DataFrame
print(df)


   Name  Age      City
0  John   25  New York
1  Jane   30    London
2  Mike   35     Paris


In [6]:
#Creating a Pandas dataframe using list of tuples

# List of tuples
data = [
    ('John', 25, 'New York'),
    ('Jane', 30, 'London'),
    ('Mike', 35, 'Paris')
]

# Creating DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

# Displaying the DataFrame
print(df)



   Name  Age      City
0  John   25  New York
1  Jane   30    London
2  Mike   35     Paris


In [7]:
#Create a Pandas DataFrame from List of Dicts


# List of dictionaries
data = [
    {'Name': 'John', 'Age': 25, 'City': 'New York'},
    {'Name': 'Jane', 'Age': 30, 'City': 'London'},
    {'Name': 'Mike', 'Age': 35, 'City': 'Paris'}
]

# Creating DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)


   Name  Age      City
0  John   25  New York
1  Jane   30    London
2  Mike   35     Paris


In [8]:
# Creating a dataframe from Pandas series


# Creating a Pandas Series
series = pd.Series([10, 20, 30, 40, 50], name='Numbers')

# Creating DataFrame from Series
df = pd.DataFrame(series)

# Displaying the DataFrame
print(df)


   Numbers
0       10
1       20
2       30
3       40
4       50


In [9]:
#Reindexing in Pandas DataFrame

# Creating a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c'])

# Reindexing rows
df_reindexed = df.reindex(['c', 'b', 'a'])

# Displaying the reindexed DataFrame
print(df_reindexed)


   A  B
c  3  6
b  2  5
a  1  4


In [10]:
#Reset Index in Pandas Dataframe

# Creating a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c'])

# Resetting the index
df_reset = df.reset_index()

# Displaying the DataFrame with reset index
print(df_reset)


  index  A  B
0     a  1  4
1     b  2  5
2     c  3  6


In [11]:
#Change column names and row indexes in Pandas DataFrame

# Creating a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

# Changing column names
df.columns = ['X', 'Y', 'Z']

# Displaying the DataFrame with new column names
print(df)


   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9


# 7.Pandas Dataframe Row Exercises

In [12]:
#How to iterate over rows in Pandas Dataframe

# Creating a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Iterating over rows using iterrows()
for index, row in df.iterrows():
    print(index, row['A'], row['B'])


0 1 4
1 2 5
2 3 6


In [13]:
# Different ways to iterate over rows in Pandas Dataframe


# Creating a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Iterating over rows using indexing and iteration
for i in range(len(df)):
    row = df.iloc[i]
    print(row['A'], row['B'])


1 4
2 5
3 6


In [3]:
#Selecting rows in pandas DataFrame based on conditions

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Select rows where Age is greater than 30
selected_rows = df[df['Age'] > 30]

print(selected_rows)


      Name  Age    City
2  Charlie   35   Paris
3    David   40   Tokyo
4      Eve   45  Sydney


In [6]:
#Select any row from a Dataframe using iloc[] and iat[] in Pandas
# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Select the first row using iloc[]
first_row = df.iloc[0]

# Select the value from the second row and 'Name' column using iat[]
value = df.iat[1, 0]

print(first_row)
print(value)

Name       Alice
Age           25
City    New York
Name: 0, dtype: object
Bob


In [8]:
#Limited rows selection with given column in Pandas | Python

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Select the first three rows based on the 'Name' column
limited_rows = df.head(3)

print(limited_rows)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [9]:
#Drop rows from the dataframe based on certain condition applied on a column

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Drop rows where Age is greater than 30
filtered_df = df.drop(df[df['Age'] > 30].index)

print(filtered_df)


    Name  Age      City
0  Alice   25  New York
1    Bob   30    London


In [12]:
#Insert row at given position in Pandas Dataframe

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Eve'],
        'Age': [25, 30, 35, 45],
        'City': ['New York', 'London', 'Paris', 'Sydney']}
df = pd.DataFrame(data)

# Create a new row
new_row = {'Name': 'David', 'Age': 40, 'City': 'Tokyo'}

# Insert the new row at position 2
df = df.loc[:1].append(new_row, ignore_index=True).append(df.loc[2:], ignore_index=True)

print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2    David   40     Tokyo
3  Charlie   35     Paris
4      Eve   45    Sydney


C:\Users\Tcc\AppData\Local\Temp\ipykernel_14640\2812240325.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.loc[:1].append(new_row, ignore_index=True).append(df.loc[2:], ignore_index=True)
C:\Users\Tcc\AppData\Local\Temp\ipykernel_14640\2812240325.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.loc[:1].append(new_row, ignore_index=True).append(df.loc[2:], ignore_index=True)


In [13]:
# Create a list from rows in Pandas dataframe

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Convert DataFrame rows into a list
rows_list = df.values.tolist()

print(rows_list)


[['Alice', 25, 'New York'], ['Bob', 30, 'London'], ['Charlie', 35, 'Paris']]


In [14]:
#Ranking Rows of Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Score': [85, 90, 75, 80, 95]}
df = pd.DataFrame(data)

# Rank the rows based on the 'Score' column
df['Rank'] = df['Score'].rank(ascending=False)

print(df)


      Name  Score  Rank
0    Alice     85   3.0
1      Bob     90   2.0
2  Charlie     75   5.0
3    David     80   4.0
4      Eve     95   1.0


In [15]:
#Sorting rows in pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Sort the rows based on the 'Age' column in ascending order
sorted_df = df.sort_values(by='Age', ascending=True)

print(sorted_df)


      Name  Age      City
3    David   20     Tokyo
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
4      Eve   45    Sydney


In [16]:
# Select row with maximum and minimum value in Pandas dataframe


# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Select the row with the maximum value across all columns
max_row = df.loc[df.values.argmax(axis=0)]

# Select the row with the minimum value across all columns
min_row = df.loc[df.values.argmin(axis=0)]

print("Row with the maximum value:")
print(max_row)
print()
print("Row with the minimum value:")
print(min_row)


Row with the maximum value:
      Name  Age   City
2  Charlie   35  Paris
2  Charlie   35  Paris
2  Charlie   35  Paris

Row with the minimum value:
    Name  Age      City
0  Alice   25  New York
0  Alice   25  New York
1    Bob   30    London


In [17]:
#Get all rows in a Pandas DataFrame containing given substring

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Define the substring to search for
substring = 'ar'

# Get all rows containing the substring in the 'Name' column
rows_with_substring = df[df['Name'].str.contains(substring)]

print(rows_with_substring)


      Name  Age   City
2  Charlie   35  Paris


In [18]:
# Convert a column to row name/index in Pandas


# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Set the 'Name' column as the new index
df = df.set_index('Name')

print(df)


         Age      City
Name                  
Alice     25  New York
Bob       30    London
Charlie   35     Paris
David     20     Tokyo
Eve       45    Sydney


In [19]:
#How to randomly select rows from Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}
df = pd.DataFrame(data)

# Randomly select 3 rows from the DataFrame
random_rows = df.sample(n=3)

print(random_rows)


    Name  Age      City
3  David   20     Tokyo
4    Eve   45    Sydney
0  Alice   25  New York


# 8. Pandas Dataframe Column Exercise

In [21]:
#Create a pandas column using for loop

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Create a new column 'Category' based on 'Age' values
df['Category'] = ''

# Iterate over the rows and assign values to the new column
for index, row in df.iterrows():
    age = row['Age']
    if age < 30:
        category = 'Young'
    else:
        category = 'Old'
    df.loc[index, 'Category'] = category

print(df)


      Name  Age Category
0    Alice   25    Young
1      Bob   30      Old
2  Charlie   35      Old
3    David   20    Young
4      Eve   45      Old


In [22]:
#How to get column names in Pandas dataframeimport pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Get the column names
column_names = df.columns

print(column_names)


Index(['Name', 'Age', 'City'], dtype='object')


In [23]:
#How to rename columns in Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Rename columns
df = df.rename(columns={'Name': 'Full Name', 'Age': 'Age (in years)'})

print(df)


  Full Name  Age (in years)      City
0     Alice              25  New York
1       Bob              30    London
2   Charlie              35     Paris


In [24]:
#Get unique values from a column in Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
        'Age': [25, 30, 25, 35, 30]}
df = pd.DataFrame(data)

# Get unique values from the 'Name' column
unique_names = df['Name'].unique()

print(unique_names)


['Alice' 'Bob' 'Charlie']


In [25]:
#Return the Index label if some condition is satisfied over a column in Pandas Dataframe

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Find index labels where the Age is greater than 30
indices = df.loc[df['Age'] > 30].index

print(indices)


Int64Index([2, 4], dtype='int64')


In [26]:
#Create a new column in Pandas DataFrame based on the existing columns

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45],
        'Salary': [50000, 60000, 70000, 55000, 80000]}
df = pd.DataFrame(data)

# Create a new column 'Salary Increase' based on 'Salary' column
df['Salary Increase'] = df['Salary'] * 0.1

print(df)


      Name  Age  Salary  Salary Increase
0    Alice   25   50000           5000.0
1      Bob   30   60000           6000.0
2  Charlie   35   70000           7000.0
3    David   20   55000           5500.0
4      Eve   45   80000           8000.0


In [27]:
#Creating a Pandas dataframe column based on a given condition
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Create a new column 'Category' based on the condition
df.loc[df['Age'] < 30, 'Category'] = 'Young'
df.loc[df['Age'] >= 30, 'Category'] = 'Old'

print(df)


      Name  Age Category
0    Alice   25    Young
1      Bob   30      Old
2  Charlie   35      Old
3    David   20    Young
4      Eve   45      Old


In [28]:
#Getting frequency counts of a columns in Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Alice'],
        'Age': [25, 30, 35, 20, 25]}
df = pd.DataFrame(data)

# Get frequency counts of the 'Name' column
counts = df['Name'].value_counts()

print(counts)


Alice      2
Bob        1
Charlie    1
David      1
Name: Name, dtype: int64


In [29]:
#Split a text column into two columns in Pandas DataFrame

# Create a sample DataFrame
data = {'Full Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown']}
df = pd.DataFrame(data)

# Split the 'Full Name' column into 'First Name' and 'Last Name'
df[['First Name', 'Last Name']] = df['Full Name'].str.split(' ', 1, expand=True)

print(df)


       Full Name First Name Last Name
0    Alice Smith      Alice     Smith
1    Bob Johnson        Bob   Johnson
2  Charlie Brown    Charlie     Brown


C:\Users\Tcc\AppData\Local\Temp\ipykernel_14640\2446725248.py:8: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['First Name', 'Last Name']] = df['Full Name'].str.split(' ', 1, expand=True)


In [31]:
#Get the index of minimum value in DataFrame column

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Get the index of the minimum value in the 'Age' column
min_index = df['Age'].argmin()

print(min_index)


3


In [33]:
#Get the index of maximum value in DataFrame column

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Get the index of the maximum value in the 'Age' column
max_index = df['Age'].argmax()

print(max_index)


4


In [34]:
#Difference of two columns in Pandas dataframe

# Create a sample DataFrame
data = {'A': [10, 20, 30, 40, 50],
        'B': [5, 12, 25, 35, 45]}
df = pd.DataFrame(data)

# Calculate the difference between columns 'A' and 'B'
df['Difference'] = df['A'] - df['B']

print(df)


    A   B  Difference
0  10   5           5
1  20  12           8
2  30  25           5
3  40  35           5
4  50  45           5


In [35]:
#Get n-largest values from a particular column in Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Get the 3 largest values from the 'Age' column
n_largest = df['Age'].nlargest(3)

print(n_largest)


4    45
2    35
1    30
Name: Age, dtype: int64


In [36]:
#Get n-smallest values from a particular column in Pandas DataFrame

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 20, 45]}
df = pd.DataFrame(data)

# Get the 2 smallest values from the 'Age' column
n_smallest = df['Age'].nsmallest(2)

print(n_smallest)


3    20
0    25
Name: Age, dtype: int64


In [37]:
#How to drop one or multiple columns in Pandas Dataframe

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Gender': ['Female', 'Male', 'Male'],
        'Salary': [50000, 60000, 70000]}
df = pd.DataFrame(data)

# Drop the 'Gender' and 'Salary' columns
df = df.drop(columns=['Gender', 'Salary'])

print(df)




      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


# 9. Pandas Series - Practise Excercise

In [3]:
#Create a Pandas Series from array


# Create an array
my_array = np.array([10, 20, 30, 40, 50])

# Create a Pandas Series from the array
my_series = pd.Series(my_array)

# Print the Series
print(my_series)


0    10
1    20
2    30
3    40
4    50
dtype: int32


In [4]:
#Creating a Pandas Series from Dictionary

# Create a dictionary
my_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50}

# Create a Pandas Series from the dictionary
my_series = pd.Series(my_dict)

# Print the Series
print(my_series)


A    10
B    20
C    30
D    40
E    50
dtype: int64


In [5]:
# Creating a Pandas Series from Lists
import pandas as pd

# Create a list
data_list = [10, 20, 30, 40, 50]
index_list = ['A', 'B', 'C', 'D', 'E']

# Create a Pandas Series from the lists
my_series = pd.Series(data_list, index=index_list)

# Print the Series
print(my_series)


A    10
B    20
C    30
D    40
E    50
dtype: int64


In [6]:
#Create Pandas Series using NumPy functions

# Create an array using NumPy functions
my_array = np.linspace(0, 1, num=5)  # Generates 5 evenly spaced values between 0 and 1

# Create a Pandas Series from the array
my_series = pd.Series(my_array)

# Print the Series
print(my_series)


0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


In [7]:
# Access the elements of a Series in Pandas


# Create a Series
my_series = pd.Series([10, 20, 30, 40, 50])

# Access the second element of the Series
value = my_series[1]

print(value)


20


# 10. Pandas Datetime Excercise

In [8]:
#Convert the column type from string to datetime format in Pandas dataframe


# Create a sample DataFrame
data = {'Date': ['2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01'],
        'Value': [10, 20, 30, 40]}

df = pd.DataFrame(data)

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Print the DataFrame with the updated column type
print(df)


        Date  Value
0 2021-05-01     10
1 2021-06-01     20
2 2021-07-01     30
3 2021-08-01     40
